### ISSUE TITLE
Feature: Would be good to have startup projects appear bold in the tree

### ISSUE THREAD

**Issue by i00** [niklashempel/SetMultipleStartupProjects#1]
If there is a single startup project it appears as bold in the Solution Explorer tree.
It would be good if your Extension could make this work for multiple startup projects also!

Thanks

**Comment by niklashempel** [comment]
I will have a look into it

**Comment by niklashempel** [comment]
It seems to not be possible at the moment. The default behaviour of visual studio is that the solution name appears bold if there are mutiple startup projects.
